### ISSUE TITLE
Homebrew launcher channel install error 0xFFBF422

### ISSUE THREAD

**Issue by Datasnuten** [FlimFlam69/WiiUTutorial#11]
EU consol. Appears when attempted to be installed through WUP installer mod. Not that it matters much since the Haxchi icon gives me access to the homebrew channel anyway. Non-CFW installations installs fine while e-shop games for example returns the same exact same error (0xFFBF422) as the homebrew launcher channel

**Comment by FlimFlam69** [comment]
Hey, in the future - please submit questions like this to the [/r/WiiUHacks](https://www.reddit.com/r/WiiUHacks/comments/5hbn9v/wiiu_hacking_qa_general_why_does_my_console_not/) Q&A thread.

You need to be running **HaxchiFW** or **Mocha CFW** before installing eShop Games, DLC, VC games, out-of-region games, and the Homebrew Launcher Channel. 

There are no issues with the guide (which is what this section is for), as it instructs you to:

* Install the HBL channel after running **Haxchi FW**

* Warns you 3 times about running **HachiFW** or **Mocha CFW** before installing eShop Games, DLC, VC games, and out-of-region games.

**Comment by Datasnuten** [comment]
There obviously is some problem with the guide when people follow it down to every line and they get the same problem, as seen in the reddit thread. How are you denying this? 

>questions like this

It's not a question, it's an error people are getting when they follow your guide.

>Install the HBL channel after running Haxchi FW

The submitted issue states this is not possible in the first place following your guide. Don't kid yourself.

Maybe you should revise the guide with some solution to this problem in the reddit thread. I wrote down a solution that works in the thread, for example.
