### ISSUE TITLE
config.txt for Mocha is incorrect

### ISSUE THREAD

**Issue by klave7** [FlimFlam69/WiiUTutorial#13]
The config.txt in 4) Installing redNAND with Mocha CFW step 3 is incorrect.  It is set to default to sysmenu when it should be pointing to wiiu/apps/mocha/mocha.elf

**Comment by FlimFlam69** [comment]
Shit! You're right, I'll fix this ASAP.

Whoops!

**Comment by FlimFlam69** [comment]
All set, thanks for letting me know
