### ISSUE TITLE
Mocha CFW crashing on startup

### ISSUE THREAD

**Issue by holychwan** [FlimFlam69/WiiUTutorial#14]
So I finished the guide, everything was alright, and now suddenly when I launch Haxchi, It gets stuck on the Mocha CFW splash screen.

Cheers
UPDATE: I'm redumping the NAND, gonna see if after doing this it works again
UPDATE 2: OK it works now, but before closing, can anyone tell me how to get the backup from the SD Card?
UPDATE 3: The games I installed don't work anymore, says something about data and needs to be uninstalled, any help?

**Comment by yllapilate** [comment]
@CJCTheNoob Hey, I'm having very similar issues (you can see the details [here](https://github.com/dimok789/mocha/issues/6) and [here](https://www.reddit.com/r/WiiUHacks/comments/5hbn9v/wiiu_hacking_qa_general_why_does_my_console_not/dbchi9y/)). I don't yet have games installed on my Wii U so I'm not worried about damage that can be done there. So, I'm currently trying to redump the NAND, but whenever I "confirm and exit" (i.e., when I press "A") from the boot options in Mocha, it just boots Mocha up and subsequently hangs. Can you offer advice as to how to trigger a redump of the NAND memory for Mocha?

**Comment by holychwan** [comment]
Use [this](https://www.sdcard.org/downloads/formatter_4/eula_windows/SDFormatterv4.zip) following [this](http://kb.sandisk.com/app/answers/detail/a_id/14827/~/using-sd-formatter-tool-to-restore-full-capacity-on-sdhc%2Fsdxc-cards) to format your SD card, put the backup files inside the SD card again and then launch Haxchi, It should start the dumping process

**Comment by yllapilate** [comment]
@CJCTheNoob Thanks a lot, that worked. It's now in the process of redumping, so hopefully it'll work...

**Comment by yllapilate** [comment]
@CJCTheNoob Hey, so the redump worked out and I've been able to get Mocha to boot (seemingly) successfully thereafter. However, I'm still seeing the `sysNAND` folder on the system menu, from Step 16 [here](https://github.com/FlimFlam69/WiiUTutorial/wiki/4:-Installing-redNAND-with-Mocha-CFW#installing-haxchi-for-mocha-cfw-with-rednand). According to the guide, I'm not supposed to see this after booting into Mocha. Do you or maybe @FlimFlam69 have any advice about this?

**Comment by holychwan** [comment]
Delete the folder sysNAND before launching Mocha, launch it and if the folder sysNAND is back then you are on Mocha.
That folder was supposed to be created after dumping, that's why you see it in Mocha.

**Comment by yllapilate** [comment]
@CJCTheNoob Ok, I see. Yes, I had created that folder before dumping, so that makes sense. It works just like you say; I deleted the folder and it reappeared after booting into Mocha. Thanks so much!
