### ISSUE TITLE
Could you add a section on using mocha for eshop?

### ISSUE THREAD

**Issue by download13** [FlimFlam69/WiiUTutorial#16]
I managed to install and play eshop titles and dlc using mocha cfw without having to buy one of the DSiWare titles listed in the guide. This works well for me since I don't mind taking an extra few seconds to load up mocha, but I really didn't want to spend the money on a dsiware title.

The thing is, I had to find this method completely through trial and error. It would be cool if this was mentioned as an alternative way to use eshop content in the guide.

**Comment by FlimFlam69** [comment]
I think what you're trying to say is that with the guide in it's current state, it's *implied* that you need to buy one of the DS VC titles listed, when you really don't need it to install these types of games (eshop, vc, dlc).

I think you're right. This is a pretty huge flaw, and I'll see what I can do to fix it. This issue will remain open until I can figure something out.

**Comment by FlimFlam69** [comment]
Added a section where it doesn't require Haxchi to run Mocha CFW. This should be all set now.
