### ISSUE TITLE
Guide says you can run Mocha from HBC, then doesn't follow up

### ISSUE THREAD

**Issue by arromdee** [FlimFlam69/WiiUTutorial#17]
Section 3 of the guide says "Note: If you are unable to buy a DS VC title, you can still run Mocha CFW from the Homebrew Channel."

However, every single part of the guide after that assumes that your running Haxchi.  I have absolutely no idea what to do in part 4, for instance, if I am not using Haxchi.

Also, I really wish there was a part of the guide "Upgrading from Loadiine".  For instance, can I use my SD card with Loadiine-ready games with MochaCFW?  (And will I keep my saves?)

**Comment by FlimFlam69** [comment]
I fixed all that for you.

I'm not going to write an "Upgrading from Loadiine" section, as it's not really necessary. It's just an app, and you can't easily just convert games for the Brazilian method (It's possible, but it's not so much of a super user friendly process yet). You're better off getting games again from NUSGrabbers anyways.

In terms of using your saves again, it's possible. I moved all my various other tutorials to the [WiiUHacks wiki](https://www.reddit.com/r/WiiUHacks/wiki/index) which is linked on the homepage, and the sidebar.
