### ISSUE TITLE
Broken "Continue to" link at bottom of section 6

### ISSUE THREAD

**Issue by JohnVeness** [FlimFlam69/WiiUTutorial#18]
At the bottom of https://github.com/FlimFlam69/WiiUTutorial/wiki/6:-Brazilian-Title-Install-Method the link labelled "Continue to vWii Modding" actually returns you to the home page of the wiki rather than to the next section. I think this is because it links to https://github.com/FlimFlam69/WiiUTutorial/wiki/6:-vWii-Modding when it should in fact link to https://github.com/FlimFlam69/WiiUTutorial/wiki/7:-vWii-Modding

**Comment by FlimFlam69** [comment]
Thanks for the heads up! All fixed!
