### ISSUE TITLE
Guide says to use wiiu filder for loadiine

### ISSUE THREAD

**Issue by arromdee** [FlimFlam69/WiiUTutorial#19]
The guide says "(Optional) Download the latest version of Loadiine. Extract the 'wiiu' folder into the root of your SD card.".  The latest version of loadiine contains no wiiu folder.

It probably should say something like "create the folder wiiu/apps/loadiine and then extract the files loadiine_gx2.elf, meta.xml, icon.png into that directory".

**Comment by FlimFlam69** [comment]
Thanks for letting me know, I'll get to fixing this
