### ISSUE TITLE
redNAND not booting the first time

### ISSUE THREAD

**Issue by Nomelas** [FlimFlam69/WiiUTutorial#20]
it looks like there's an issue with mocha not booting for the first time into redNAND after taking the dump.

See https://github.com/FlimFlam69/WiiUTutorial/wiki/4:-Installing-redNAND-with-Mocha-CFW#installing-haxchi-for-mocha-cfw-with-rednand
Step 18) Launch the Haxchi title

the fix is to create (or modify if it exists) the config.ini inside SD:\wiiu\apps\mocha\ with the following:

[MOCHA]
viewMode=1
directLaunch=1
launchImage=1
noIosReload=0
launchSysMenu=1
redNAND=1
seeprom_red=1
otp_red=1
syshaxXml=0

This may require UNIX new-line - so an upload of the file might be good for those who don't know how to do that so they can download and not have to edit the file directly.

**Comment by Hotrian** [comment]
I'm still dumping my sysNAND so I can't say for sure, but I think this is covered under `Step 11` where you configure Mocha. Is it possible you skipped or messed up this step somehow? These seem to be the same values that are set in `Step 11`, so maybe Mocha is no longer saving the file properly or you set one of the options incorrectly?

Not trying to blame user error here, I just noticed that config seems to have the same values set in `Step 11` so I think the guide was correct at some time and something went wrong with your install, or possibly something is wrong with the revision of Mocha CFW's configurator you used.

Will update with results once my redNAND is ready.

Edit: My redNAND booted right up first try, didn't have to mess with anything, though it did take me back to the Mocha CFW Configurator, I just set the options up the way they were in `Step 11` and went on my way :).

**Comment by Nomelas** [comment]
:)

but yeah, either way it seems

**Comment by curtisy1** [comment]
Well, it's a rare occasion but since it happened to two users independently, I would say it's probably a tiny flaw in Mocha. @Nomelas what region is your Wii U? Nonetheless, this is useful information. Thanks again for testing this for me :).

**Comment by Nomelas** [comment]
Another on discord had the same issue. I'm in Canada but I assume its all NA
