### ISSUE TITLE
Suggest put config.txt in Starter Pack

### ISSUE THREAD

**Issue by JohnVeness** [FlimFlam69/WiiUTutorial#21]
In https://github.com/FlimFlam69/WiiUTutorial/wiki/3:-Installing-HaxchiFW-&-The-Homebrew-Launcher-Channel steps 1 to 7 are in the Starter Pack instructions. I'm suggesting to put steps 8 and 9 in the Starter Pack instructions too. That way people who have followed those instructions and moved the SD from the PC to the Wii U won't have to transfer it back again, as they currently have to do.

**Comment by JohnVeness** [comment]
Reading on I see there is a different config.txt in https://github.com/FlimFlam69/WiiUTutorial/wiki/4:-Installing-redNAND-with-Mocha-CFW which maybe explains why there isn't one in the Starter Pack. But I don't really understand why you cannot simply run mocha.elf from the Homebrew Launcher rather than use a different config.txt and reinstall Haxchi.

**Comment by FlimFlam69** [comment]
Both configs do different things. Haxchi's config will launch HaxchiFW, and Mocha's will launch Mocha. These are 2 different functions, which require 2 different commands in the default position in the config files.

You can run Mocha from the HBL, but the guide outlines the most convenient way to launch it. If you have a Haxchi title, and you wan to launch redNAND, why wouldn't you want to utilize Haxchi to launch Mocha CFW redNAND? Launching from HBL adds more clicks to the process.

**Comment by JohnVeness** [comment]
Thanks. Having read it a bit more I now understand the difference. I'll make one more comment which you can consider then I'll be quiet on this issue.

My comment was mostly based on the fact that my PC with SD card reader is quite separate (some hours away) from my Wii U. I thought I had done well doing everything in the Starter Pack, so it was annoying when I found out I had to revisit the PC! I realise this might not be as big an issue for everyone.

Maybe one solution that wouldn't adversely affect anyone would be to put the https://github.com/FlimFlam69/WiiUTutorial/wiki/3:-Installing-HaxchiFW-&-The-Homebrew-Launcher-Channel config.txt into the Starter Pack setup. That way, someone can go into Stage 3 without having to revisit a PC. They will need to revisit a PC to do Stage 4 (if they chose to do it, which many people will not), to change the config.txt, but they would have to revisit a PC anyway in order to backup the SD card.

As you say, actually changing the config.txt for Stage 4 is not 100% necessary, or at least, not straight away. You could have the instructions setup in such a way that the config.txt doesn't change initially, you explain how to run Mocha and do the rednand setup. There could then be a bit at the bottom saying something like "If you want quicker access into Mocha, proceed as follows" and doing the config.txt change and reinstalling Haxchi. Why do things this way round you might ask? I would argue that it makes it clearer exactly why you're reinstalling Haxchi.
