### ISSUE TITLE
Wrong "continue to" at bottom of stage 4

### ISSUE THREAD

**Issue by JohnVeness** [FlimFlam69/WiiUTutorial#22]
At the bottom of https://github.com/FlimFlam69/WiiUTutorial/wiki/4:-Installing-redNAND-with-Mocha-CFW the "continue to" link is to disc2app, when it should be to CBHC.

**Comment by FlimFlam69** [comment]
It's not an issue, I purposely did this. It's my passive way of saying, don't use CBHC unless you need to.
