### ISSUE TITLE
Disc2app section should say to wipe install folder first

### ISSUE THREAD

**Issue by JohnVeness** [FlimFlam69/WiiUTutorial#24]
In https://github.com/FlimFlam69/WiiUTutorial/wiki/6:-disc2app I found that everything worked up to the install game stage. Turned ouf this was because the install folder wasn't empty, as it still had the Homebrew Launcher Channel stuff in it, which it would still do for anyone following the guide as written. I think you should add a note saying to wipe the install folder before dumping a disc.

Also on the same page there's a typo in "completeing".

**Comment by FlimFlam69** [comment]
All set.
