### ISSUE TITLE
Instructions regarding Loadiine out of date?

### ISSUE THREAD

**Issue by SunsetOrange** [FlimFlam69/WiiUTutorial#27]
In the "Making Your Own Starter Pack" section of the guide, there is an optional step involving adding Loadiine to the SD card. The instructions are to "Extract the 'wiiu' folder into the root of your SD card".
The Loadiine download pack does not contain a wiiu folder to merge with the SD card. Can you please update or clarify that step with new instructions.
Cheers

**Comment by FlimFlam69** [comment]
Removed it all together. Loadiine isn't relevant to the guide anyways.
