### ISSUE TITLE
Two wiiu folders in root of SD card?

### ISSUE THREAD

**Issue by honkyjesus** [FlimFlam69/WiiUTutorial#29]
Sorry for sounding noobish, but in the Starter Pack we are to create a new folder called "wiiu" but also extract a separate wiiu folder into the root of the SD card? How can two folders named the same thing be done?

**Comment by nreymundo** [comment]
Hey!, when you extract a folder with the same name to the root of the SD card the contents should be merged with the already existing content in that folder. You should end with just 1 folder with all the appropriate content inside.

**Comment by honkyjesus** [comment]
Thanks, I will try that.

**Comment by honkyjesus** [comment]
That worked, I knew it was something stupid on my end. Closed.
