### ISSUE TITLE
Haxchi_Installer fails to install on older version of Brain Age

### ISSUE THREAD

**Issue by twig** [FlimFlam69/WiiUTutorial#4]
Under the section [Installing Haxchi](https://github.com/FlimFlam69/WiiUTutorial/wiki/3:-IOSUhax-and-Haxchi#installing-haxchi), please include a note that says "make sure your copy of brain age is up to date".

This is from the forum post troubleshooting notes:

> 4) The icons are good but the NDS game (Brain Age) starts instead
> This is because you have an old version of the NDS game that doesnt work, try deleting it and download it again from eShop.

It was a huge waste of time for me because it took forever to install the custom image/icon/sounds for the channel icon.

**Comment by FlimFlam69** [comment]
Sorry about that. I'll make a note of this and close this issue when I do.

**Comment by twig** [comment]
It was only a huge waste of time under the old Python installer script.

With haxchi 2 installer it should be pretty quick, but at least it won't confuse the user when the normal game starts up.

**Comment by FlimFlam69** [comment]
Alright, the note has been added.
