### ISSUE TITLE
vWii Virtual Console (VC) is exclusive to sysNAND (doesn't work in redNAND)

### ISSUE THREAD

**Issue by jaxrogers2** [FlimFlam69/WiiUTutorial#5]
Just something to add, vWii doesn't work in redNAND, but it does work on sysNAND, so vWii games installed via Brazilian Title Method cannot be used in redNAND. They must be run via CFW patched sysNAND OR by running the sysNAND sigpatches "exit toapp in HBL to work. Even vWii VC games that are legitimately bought from the eShop will not work in redNAND.
RedNAND users with haxchi on sysNAND could change their config to use the "exit to system menu" version of the sysNAND sigpatches Homebrew Launcher app (it's on WiiuBru) instead of a CFW sysNAND fw.img. Then, the redNAND fw.img can be used as normal from haxchi, and vWii VC games can still be used on sysNAND by running the sigpatches without fw.img HBL app.

**Comment by FlimFlam69** [comment]
Yea, you're right about this. I didn't think to mention it. When I do I'll close this issue.

**Comment by FlimFlam69** [comment]
Everything from the initial post has been explained.
