### ISSUE TITLE
Mocha CFW with redNAND issue

### ISSUE THREAD

**Issue by waltwhitman6969** [FlimFlam69/WiiUTutorial#8]
I decided to use the Mocha CFW with redNAND steps because it seemed like that was the way to go since it prevents you from bricking the entire Wii U but after moving on to the next steps, such as basically anything in the vWii Modding section, it looks like I can't do anything else.

I'm a newb to homebrew but I can do basically anything with instructions and so far have had no issue. I'm just a little confused as to what my next steps are. (how to load game backups, what else I have to install, etc..)

Any help would be appreciated. Thank you so much for this guide

**Comment by rsanch1** [comment]
If you want to mod the vWii that is the only way.  And you can brick your WiiU with rednand if you accidentally update the firmware in rednand.  Update the firmware in WiiU and you lose rednand.

Your other questions are outside the scope of this tutorial. My advice is to just do a google search on what it is that you want to accomplish and follow the guides from the other websites.

**Comment by FlimFlam69** [comment]
vWii does not work with redNAND, The guide states this in section 4.

Thank you for your kind words.
