### ISSUE TITLE
Few problems CHBC 1.4

### ISSUE THREAD

**Issue by DTK21** [FlimFlam69/WiiUTutorial#9]
Everything installed well but few errors came up

1. SYNC on wii u or gamepad  doesn't bring up the menu

2. Every time exiting game, app, anything that'll bring up the "Wii U Menu screen" autoboots cfw then loops

3. The 1.4 HBL on the Loadiine HBL site freezes but 1.3 works just fine

4. Exiting 1.3 HBL or even installing a game with Wupinstaller has the same problem like in problem # 2

**Comment by FlimFlam69** [comment]
If the SYNC button doesn't bring up the menu, or CBHC doesn't work well with certain versions of HBL, then this is a problem for FIX94 to solve - not me.
